// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiq5DhWDTVox--XCZqn6AR96Fl6XFCiN0',
    appId: '1:489305052451:web:6e4c313e868a03940ee896',
    messagingSenderId: '489305052451',
    projectId: 'avora-d943b',
    authDomain: 'avora-d943b.firebaseapp.com',
    storageBucket: 'avora-d943b.firebasestorage.app',
    measurementId: 'G-0MKKY82363',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRarrXMA4uSKIVRL8TM3vo_bLWEvqfrYI',
    appId: '1:489305052451:android:a246e67a330b06640ee896',
    messagingSenderId: '489305052451',
    projectId: 'avora-d943b',
    storageBucket: 'avora-d943b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwU9pS_XXVq2Lt5xpigRwiakr0brU_DO4',
    appId: '1:489305052451:ios:293056a82c9ddb010ee896',
    messagingSenderId: '489305052451',
    projectId: 'avora-d943b',
    storageBucket: 'avora-d943b.firebasestorage.app',
    iosBundleId: 'com.example.avora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwU9pS_XXVq2Lt5xpigRwiakr0brU_DO4',
    appId: '1:489305052451:ios:293056a82c9ddb010ee896',
    messagingSenderId: '489305052451',
    projectId: 'avora-d943b',
    storageBucket: 'avora-d943b.firebasestorage.app',
    iosBundleId: 'com.example.avora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiq5DhWDTVox--XCZqn6AR96Fl6XFCiN0',
    appId: '1:489305052451:web:40a00019dccccf610ee896',
    messagingSenderId: '489305052451',
    projectId: 'avora-d943b',
    authDomain: 'avora-d943b.firebaseapp.com',
    storageBucket: 'avora-d943b.firebasestorage.app',
    measurementId: 'G-X92JT8FG7L',
  );
}
